### ISSUE TITLE
Does not compile on Fedora 25

### ISSUE THREAD

**Issue by blackwolf12333** [amazari/rhythmbox-spotify#1]
This plugin won't compile with the version of rhythmbox that is installed by default on Fedora 25 with the following error:

`/usr/include/rhythmbox/sources/rb-source.h:37:37: fatal error: widgets/rb-search-entry.h: No such file or directory
 #include <widgets/rb-search-entry.h>
`

The version of Rhythmbox is 3.4.1

**Comment by blackwolf12333** [comment]
~I just realized this might be a packaging issue by fedora, and not a problem with this repo.~

Jup, pretty sure that's it. however I still get another error.

`rb-spotify-src.c:109:8: error: unknown type name ‘GstElementDetails’`

Which might have to do with the fact that GstElementDetails is deprecated.

**Comment by amazari** [comment]
Hi blackwolf12333,

Thanks for your interest in the project. Sadly I haven't really been working on it for the last 6y. Gstreamer, libspotify and rhythmbox APIs evolved immensely in the mean time and rebasing this code would be quite an undertaking. To be honest, I don't use rnb anymore and the official client is available on linux so my interest in updating it faded. Feel free to fork, of course!
 
FWIW it did not really work correctly in the first place anyway. There are some alternative players around with which you might have better success: https://www.reddit.com/r/spotify/comments/3w1yui/lightweight_spotify_alternatives_are_there_any/

Enjoy your music.

**Comment by blackwolf12333** [comment]
Hi,

Thanks for the response. I might fork this, we'll see if I can bring up the interest to work on it myself :P
